### ISSUE TITLE
Terraform Docker Image Does Not Exist

### ISSUE THREAD

**Issue by as0bu** [drone-plugins/drone-terraform#10]
During the Drone build I get the following error:

```
[info] Pulling image plugins/drone-terraform:latest
[info] Pulling image plugins/drone-terraform:latest
[error] Error pulling plugins/drone-terraform:latest. Tag latest not found in repository docker.io/plugins/drone-terraform

[info] build failed (exit code 255)
```

When I go look for the image on DockerHub it does not exist either.

**Comment by as0bu** [comment]
I just noticed that the build was failing, and I'm guessing this is why it doesn't exist. I also noticed that the .drone.sec file is not present which I believe would have your encrypted dockerhub username/password. Again a lot of this is speculation and please correct me if I'm wrong.

**Comment by jackspirou** [comment]
@as0bu your speculation is correct. I believe @bradrydzewski needs to add the `.drone.sec`.  @tboerger  correct me if I am wrong.

**Comment by tboerger** [comment]
I will create a PR to add it now

**Comment by as0bu** [comment]
Awesome, thanks @tboerger!

**Comment by tboerger** [comment]
Will be fixed with https://github.com/drone-plugins/drone-terraform/pull/11
