### ISSUE TITLE
modules are not downloaded

### ISSUE THREAD

**Issue by jeffastorey** [drone-plugins/drone-terraform#15]
terraform modules are not downloaded using terraform get before running commands. any builds using modules will fail

**Comment by tboerger** [comment]
Which modules?

**Comment by jeffastorey** [comment]
In general if you have a terraform file that depends on other modules, they don't get downloaded before the terraform run.

**Comment by tboerger** [comment]
But this is resolved with https://github.com/drone-plugins/drone-terraform/pull/16 or not?

**Comment by jeffastorey** [comment]
Yes I think the issue just needs to be closed. Thought one of the maintainers closes it, but I'm happy to
